CC-25632: Updated builder for Node v18
spryker/jQuery-QueryBuilder pull request #4
Opened 2023-05-02 17:56 UTC by andrew-maslov

Ticket: https://spryker.atlassian.net/browse/CC-25632

2023-05-11 11:11 UTC, FRITS-Kh requested changes

2023-05-11 11:11 UTC, FRITS-Kh commented on .travis.yml
> +  - "16"
Please replace to
```
dist: jammy
language: node_js
node_js: 18
cache:
    npm: true
```

2023-05-11 11:11 UTC, FRITS-Kh commented on dist/css/query-builder.dark.css
> + * Copyright 2014-2023 Damien "Mistic" Sorel (http://www.strangeplanet.fr)
Why do we change the license info?

2023-05-11 11:11 UTC, FRITS-Kh commented on dist/js/query-builder.standalone.js
> + * Copyright 2014-2016 Damien "Mistic" Sorel (http://www.strangeplanet.fr)
Maybe it should be:
```suggestion
 * Copyright 2014-2023 Damien "Mistic" Sorel (http://www.strangeplanet.fr)
```

2023-10-22 18:50 UTC, closed without merging

2023-10-22 18:51 UTC, andrew-maslov commented
Closed PR since the repository will be deprecated.